name: Project Build

on:
  push:
  release:
    types:
      - published

jobs:
  build-server:
    strategy:
      matrix:
        version:
          #- 8
          - 7.0.x
        os: 
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.version}}
      - name: Build Game Server
        run: make build-server
      - name: Build Game Client
        run: make build-client

      # Only run on releases
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }} 
        with:
          files: Source/Server/bin/Release/net7.0/Server/GameServer  
